# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: wrappers/python/docs/source/conf.py

formats:
  - htmlzip

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  system_packages: true
  install:
    - requirements: .ci/requirements.txt
    - requirements: wrappers/python/docs/requirements.txt
    - requirements: wrappers/python/requirements.txt
