# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wirepas_messaging/wnt/positioning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wirepas_messaging.nanopb import nanopb_pb2 as wirepas__messaging_dot_nanopb_dot_nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wirepas_messaging/wnt/positioning.proto',
  package='com.wirepas.proto.wpe',
  syntax='proto2',
  serialized_pb=_b('\n\'wirepas_messaging/wnt/positioning.proto\x12\x15\x63om.wirepas.proto.wpe\x1a%wirepas_messaging/nanopb/nanopb.proto\"\xc4\x01\n\x08MeshData\x12\x0e\n\x06source\x18\x01 \x01(\x04\x12\x0f\n\x07network\x18\x02 \x01(\x04\x12\x0c\n\x04sink\x18\x03 \x01(\x04\x12\x0f\n\x07version\x18\x04 \x01(\x02\x12\x10\n\x08sequence\x18\x05 \x01(\r\x12\x13\n\x0btravel_time\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\x04\x12>\n\x07payload\x18\x08 \x03(\x0b\x32&.com.wirepas.proto.wpe.MeasurementDataB\x05\x92?\x02\x10\x1e\"\xe9\x01\n\x0fMeasurementData\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.com.wirepas.proto.wpe.MeasurementData.DOMAIN\x12\x0e\n\x06target\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0c\n\x04time\x18\x04 \x01(\x02\"l\n\x06\x44OMAIN\x12\x0c\n\x08POWER_SR\x10\x00\x12\x0c\n\x08POWER_HR\x10\x01\x12\x08\n\x04TIME\x10\x02\x12\t\n\x05SPACE\x10\x03\x12\x11\n\rPOWER_SR_RSSI\x10\n\x12\x11\n\rPOWER_HR_RSSI\x10\x0b\x12\x0b\n\x06IGNORE\x10\xf0\x01')
  ,
  dependencies=[wirepas__messaging_dot_nanopb_dot_nanopb__pb2.DESCRIPTOR,])



_MEASUREMENTDATA_DOMAIN = _descriptor.EnumDescriptor(
  name='DOMAIN',
  full_name='com.wirepas.proto.wpe.MeasurementData.DOMAIN',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POWER_SR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER_HR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPACE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER_SR_RSSI', index=4, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER_HR_RSSI', index=5, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGNORE', index=6, number=240,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=430,
  serialized_end=538,
)
_sym_db.RegisterEnumDescriptor(_MEASUREMENTDATA_DOMAIN)


_MESHDATA = _descriptor.Descriptor(
  name='MeshData',
  full_name='com.wirepas.proto.wpe.MeshData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='com.wirepas.proto.wpe.MeshData.source', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='com.wirepas.proto.wpe.MeshData.network', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sink', full_name='com.wirepas.proto.wpe.MeshData.sink', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.wirepas.proto.wpe.MeshData.version', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='com.wirepas.proto.wpe.MeshData.sequence', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='travel_time', full_name='com.wirepas.proto.wpe.MeshData.travel_time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.wirepas.proto.wpe.MeshData.timestamp', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='com.wirepas.proto.wpe.MeshData.payload', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\036')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=302,
)


_MEASUREMENTDATA = _descriptor.Descriptor(
  name='MeasurementData',
  full_name='com.wirepas.proto.wpe.MeasurementData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.wirepas.proto.wpe.MeasurementData.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='com.wirepas.proto.wpe.MeasurementData.target', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.wirepas.proto.wpe.MeasurementData.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.wirepas.proto.wpe.MeasurementData.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MEASUREMENTDATA_DOMAIN,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=538,
)

_MESHDATA.fields_by_name['payload'].message_type = _MEASUREMENTDATA
_MEASUREMENTDATA.fields_by_name['type'].enum_type = _MEASUREMENTDATA_DOMAIN
_MEASUREMENTDATA_DOMAIN.containing_type = _MEASUREMENTDATA
DESCRIPTOR.message_types_by_name['MeshData'] = _MESHDATA
DESCRIPTOR.message_types_by_name['MeasurementData'] = _MEASUREMENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeshData = _reflection.GeneratedProtocolMessageType('MeshData', (_message.Message,), dict(
  DESCRIPTOR = _MESHDATA,
  __module__ = 'wirepas_messaging.wnt.positioning_pb2'
  # @@protoc_insertion_point(class_scope:com.wirepas.proto.wpe.MeshData)
  ))
_sym_db.RegisterMessage(MeshData)

MeasurementData = _reflection.GeneratedProtocolMessageType('MeasurementData', (_message.Message,), dict(
  DESCRIPTOR = _MEASUREMENTDATA,
  __module__ = 'wirepas_messaging.wnt.positioning_pb2'
  # @@protoc_insertion_point(class_scope:com.wirepas.proto.wpe.MeasurementData)
  ))
_sym_db.RegisterMessage(MeasurementData)


_MESHDATA.fields_by_name['payload'].has_options = True
_MESHDATA.fields_by_name['payload']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\036'))
# @@protoc_insertion_point(module_scope)
