---
username: ${WNT_ADMIN_USERNAME:-"adminuser"}
password: ${WNT_ADMIN_PASSWORD:-"adminuserpwd"}
operator_username: ${WNT_USER_USERNAME:-"operatoruser"}
operator_password: ${WNT_USER_PASSWORD:-"operatoruserpwd"}
hostname: ${WNT_HOSTNAME:-"wnthost.com"}
